### ISSUE TITLE
Build error (undefined reference to `modf')

### ISSUE THREAD

**Issue by rajendra2** [Lora-net/packet_forwarder#1]
mipsel-openwrt-linux-uclibc-gcc -L../../lora_gateway/libloragw obj/gps_pkt_fwd.o obj/parson.o obj/base64.o -o gps_pkt_fwd -lloragw -lrt -lpthread
obj/gps_pkt_fwd.o: In function `thread_down':
gps_pkt_fwd.c:(.text+0x2464): undefined reference to`modf'
../../lora_gateway/libloragw/libloragw.a(loragw_gps.o): In function `lgw_cnt2utc':

issue is fixed by adding "-lm" in all the Makefiles. Request you to review this issue and fix in next version. 

rajendra

**Comment by mcoracin** [comment]
Hello,
Thanks for notifying this issue, this will be fixed with next release.
Michael
