### ISSUE TITLE
errors and wont start, previously worked

### ISSUE THREAD

**Issue by 6d6176** [Lora-net/packet_forwarder#102]
ERROR: Failed to load fw 1
ERROR: Version of calibration firmware not expected, actual:0 expected:2
ERROR: [main] failed to start the concentrator

**Comment by chelliwell** [comment]
I've only recently got going with this stuff, but I think I've had that when the LoRa concentrator hasn't had a hardware reset.
[And be aware that the reset is, or at least may be, active _high_]

**Comment by 6d6176** [comment]
Do you know how to do a hardware reset? I have the RHF0M301 concentrator

**Comment by chelliwell** [comment]
Sorry, no idea - I use the iC880.

**Comment by mcoracin** [comment]
This is a hardware specific question, I close the issue.
