### ISSUE TITLE
A suggestion for jit_enqueue() function 

### ISSUE THREAD

**Issue by Dollar-Yao** [Lora-net/packet_forwarder#103]
For my understanding, beacon signal with a highest priority than others. So, at the time points of 128sN, it's only can be used for beacon signal, and can't be scheduled for others. So, when use jit_enqueue() function to insert a downlink to the queue.
Is it better to judge the transmit time whether is at the time points of 128sN or not when it's not a beacon signal?
For example, current time is 120s, and the three beacon signal are scheduled at 128s, 256s, 384s. But the TX_MAX_ADVANCE_DELAY is (JIT_NUM_BEACON_IN_QUEUE + 1) * 128. If there is a server hostile to schedule a downlink at time point of 512s before the time of 128s is arrived. Then the next beacon signal will not to be scheduled successfully.
Maybe we can treat the server as reliable, which transmit ClassA downlink any at the Rx windown, transmit ClassB downlink won't exceed the 128s beacon window, transmit ClassC downlink won't too early to occupy the time point for beacon signal.

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support?__hstc=212684107.579a13689e43099691e328c9248e6ecc.1623103335314.1624470656297.1624635514661.6&__hssc=212684107.6.1624635514661&__hsfp=4176385453] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
