### ISSUE TITLE
Why exit with failure on unknown data rate in packet?

### ISSUE THREAD

**Issue by albtrentadue** [Lora-net/packet_forwarder#105]
Hello
I have experienced few times packet forwarder exit on an "unknown data rate" error:
```
INFO: Received pkt from mote: 00000000 (fcnt=0)
ERROR: [up] lora packet with unknown datarate
Packet Forwarder failed to start.
$
```
This is caused by the packet parsing part from line 1700 of lora_pkt_fwd.c:

```
default:
    MSG("ERROR: [up] lora packet with unknown datarate\n");
    memcpy((void *)(buff_up + buff_index), (void *)",\"datr\":\"SF?", 12);
    buff_index += 12;
    exit(EXIT_FAILURE);
```
It seems to me that this makes the pkt_forwarder prone to modulation issues at the remote node side.
Before removing `exit(EXIT_FAILURE)`, I'd like to know why the unknown data rate shall trigger the program termination? 
Thanks in advance!

**Comment by reissjason** [comment]
The process exits as the hardware has returned an unknown value. The hardware is in a bad state and will need to be reset to recover.

I have used the packet forwarder with the exit functionality disabled and usually the device will continuously report erroneous packets from there after.

**Comment by albtrentadue** [comment]
Thanks for your answer. I'll experiment the issue and, at worst, will setup a restart cron.
