### ISSUE TITLE
How to change the CH0-CH7 upstream frequency?

### ISSUE THREAD

**Issue by zhaozhenhong5** [Lora-net/packet_forwarder#111]
I am using CN470 gateway-conf. I want to change the frequency of each upstream channel. See the config file below: For example,I changed "487.1 MHz" to "472.1 MHz" directly,but it can't work.
Do someone know how to change?
##########
		"chan_multiSF_0": {
			"desc": "Lora MAC, 125kHz, all SF, 487.1 MHz",
			"enable": true,
			"radio": 1,
			"if": -300000
		},
		"chan_multiSF_1": {
			"desc": "Lora MAC, 125kHz, all SF, 487.3 MHz",
			"enable": true,
			"radio": 1,
			"if": -100000
		},
		"chan_multiSF_2": {
			"desc": "Lora MAC, 125kHz, all SF, 487.5 MHz",
			"enable": true,
			"radio": 1,
			"if": 100000
		},
		"chan_multiSF_3": {
			"desc": "Lora MAC, 125kHz, all SF, 487.7 MHz",
			"enable": true,
			"radio": 1,
			"if": 300000
		},
		"chan_multiSF_4": {
			"desc": "Lora MAC, 125kHz, all SF, 486.3 MHz",
			"enable": true,
			"radio": 0,
			"if": -300000
		},
		"chan_multiSF_5": {
			"desc": "Lora MAC, 125kHz, all SF, 486.5 MHz",
			"enable": true,
			"radio": 0,
			"if": -100000
		},
		"chan_multiSF_6": {
			"desc": "Lora MAC, 125kHz, all SF, 486.7 MHz",
			"enable": true,
			"radio": 0,
			"if": 100000
		},
		"chan_multiSF_7": {
			"desc": "Lora MAC, 125kHz, all SF, 486.9 MHz",
			"enable": true,
			"radio": 0,
			"if": 300000
		},

**Comment by johanstokking** [comment]
Adjust the `if` considering the frequency of the concerning radio.

**Comment by zhaozhenhong5** [comment]
Thank you. And do you know how to adjust?

**Comment by cstratton** [comment]
You have to work out the offset (within the allowed range) of each IF from the corresponding radio's center frequency - is the "if" field that really matters, the description is just a description.

Someone has certainly already figured this out for your bandplan

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
