### ISSUE TITLE
Gateway: could not handle packet: gateway: unknown packet type: PullACK

### ISSUE THREAD

**Issue by agenteDserrano** [Lora-net/packet_forwarder#116]
I am using pycom.

I got a fipy running nano gateway and lopy as node.

I get connected and I can receive messages on my mqtt rx channel.

But when I try so send message back to node I have estrange behavior.

Some times I get the message (1 of 10) and other times I get ACK on mqtt ack channel but no message arrive to node.

In bridge log I see this:

Mar 20 16:14:54 loraserver.dmz.redcumbre.cl lora-gateway-bridge[30749]: time=“2019-03-20T16:14:54-03:00” level=info msg=“backend: downlink packet received” topic=gateway/30aea4fffe7907ec/tx

Mar 20 16:14:54 loraserver.dmz.redcumbre.cl lora-gateway-bridge[30749]: time=“2019-03-20T16:14:54-03:00” level=error msg=“gateway: could not handle packet: gateway: unknown packet type: PullACK” addr=“10.0.51.115:49154” data_base64=“AutmBDCupP/+eQfseyJ0eHBrX2FjayI6IHsiZXJyb3IiOiAiTk9ORSJ9fQ==”

**Comment by stankusaudrius** [comment]
I am getting exactly the same error with fipy as nano gateway and rn2483 as node. 

Downlinks are never received by the node. This results in server failing to sync with node and causes downlink attempt at every uplink.

Did you solve the issue?

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
