### ISSUE TITLE
packet forwarder with RFm96

### ISSUE THREAD

**Issue by Ala-Jeb** [Lora-net/packet_forwarder#118]
Hi everyone,
is it possible to run packet forwarder with a Raspberrypi 3 and a RFm96 module

**Comment by cstratton** [comment]
An RFM96 is a node-class radio, not a gateway radio.

It is possible to make a limited "single channel gateway" with severe limitations in usability, but this is not the software you would want to use to do that, as this software is specific to the SX1301/SX1308 multi-channel, multi-spreading-factor LoRa concentrators used in "real" gateways.  Look elsewhere online and you can find discussions of single channel gateways.

If you mean you want to use the pi and RFM96 as a node, then yes - that will communicate with this software when it is running on a suitable gateway.  But the node side of the problem isn't really on topic here.

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
