### ISSUE TITLE
ACK and stats settings on Kerlink gateways

### ISSUE THREAD

**Issue by betienneUCA** [Lora-net/packet_forwarder#124]
Hello !
I have a question about SPF settings : 

I am using a Kerlink "LoRa IoT Station 868" using SPF.
In the "global_conf.json" file, I can find these 2 lines : 

```
                "keepalive_interval": 10,
                "stat_interval": 30,
```

As I understand, the first one allows gateways to send keepalives to the server every 10 seconds, and the second one a statistic packet every 30.
I have tried to change the intervals so the gateway could send much less data (I set them both to 14400, every 4 hours) as I am transmitting through M2M GSM and do not have much credit available.

But by doing so, the packet forwarder either crashes or is only transmitting Join Requests but never actual data.

Do these values have limits ? And what are their actual impact on data reception ?
By advance, thank you very much,

Respectfully,
Etienne

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
