### ISSUE TITLE
RaspberryPi Gateway with SX1257

### ISSUE THREAD

**Issue by kungfupizza** [Lora-net/packet_forwarder#128]
Hello,
I am using a LoRaWAN concentrator based on the [design ](https://github.com/will127534/LoRa-concentrator) of Will Whang. I have set it up using [this](https://github.com/will127534/LoRa-concentrator/wiki/TTN-Network-Setup-Guide) link which uses this as packet_forwarder.

The hardware connections are properly done with RESET on GPIO25 of the Rpi and SPI host but I am getting an error as below,
![image](https://user-images.githubusercontent.com/46355685/74817011-8253fd00-52fc-11ea-9e3b-c04a2ec63939.png)

I have run various tests as in the packet forwarder and results as below,
![image](https://user-images.githubusercontent.com/46355685/74817164-c0e9b780-52fc-11ea-9f88-39632cec96ec.png)

![image](https://user-images.githubusercontent.com/46355685/74817221-dbbc2c00-52fc-11ea-841b-d442b3907f31.png)

Can someone please let me know what is going wrong?

**Comment by joau-mms** [comment]
Most Likely that's a problem with: https://github.com/Lora-net/lora_gateway have a look at the issues there and you are going to see your problems all over.
**Typical problems / fixes:**
* Concentrator does not reset properly -> Change Reset pin if wrong Pin is used and insert a delay between the pin toggle of the reset 
* The SPI frequency of 8MHz is way to high. Depending on the implementation 1-2MHz seem to be the "somewhat" stable configuration
* Sometimes the raspberries can have some odd behavior in regards of their SPI configuration.

The lora_gateway has a utility to test the SPI communication. Use it until (almost) no errors occur.


**Edit**
will127534 has git repos with already patched forwarder and gateway.
