### ISSUE TITLE
Building with exported HAL library

### ISSUE THREAD

**Issue by Patel-Apurva** [Lora-net/packet_forwarder#134]
Hello. I wish to write my own gateway code to use with a SAM3X microcontroller. I have built the HAL library to get the libloragw.a. The HAL library guide mentions the following:

![image](https://user-images.githubusercontent.com/54286544/86886652-e51e2780-c129-11ea-8cbf-a57491c506cf.png)

I read the lora_pkt_fwd Makefile and it seems to indicate that it needs to be built with the entire HAL library. How can I build lora_pkt_fwd using just the exported files mentioned above? Do I write my own code in the main function of the lora_pkt_fwd.c file?

**Comment by x893** [comment]
I ported the packet-forwarder to stm32. Not simple, but possible. Good luck.
