### ISSUE TITLE
 Configure Packet Forwarder for LG01-N for Azure IoT Hub

### ISSUE THREAD

**Issue by vermaaditya** [Lora-net/packet_forwarder#136]
Hi Team, 

I am willing to integrate the LoRa with the Azure IoT Hub using the documentation provided on - https://www.chirpstack.io/project/guides/microsoft-azure. 

As a part of this we are supposed to configure and install packet forwarder, so for that I am following the link - https://www.chirpstack.io/gateway-bridge/gateway/dragino/. I did the installation and configured my gateway with the Device Connection string which is provisioned in the Azure IoT hub, but i dont see any messages coming thru and being published. 

Please help in finding where am I missing. Nothing is coming on the logs as well.

The same gateway works fine with using with TTN.

Appreciate your prompt response. 

Thanks,

**Comment by cstratton** [comment]
The LG01 does not contain a LoRa concentrator chip supported by this repo; instead it has a node radio pretending to do the job, and relies on some non-standard software.  You'd have to pursue this with whoever maintains the software you are actually using.

Ultimately the problem may be that you are trying to use instructions for one of Dragino's actual LoRaWAN gateways that does contain a proper concentrator, on the LG01 box that has a similar _Embedded Linux_ platform but entirely different non-standard and drastically limited radio hardware.  As such, you need to use Dragino's software, not this software.  Likely even with the unique, matching software you will find the performance of the LG01 severely unsatisfactory and need to replace it with an actual LoRaWAN gateway.
