### ISSUE TITLE
GPS read() returned value 0

### ISSUE THREAD

**Issue by miqueet** [Lora-net/packet_forwarder#138]
im getting these spammed in my syslog log. I would like to turn off logging but I am not seeing that option in the configuration files or anywhere else. Can someone point me in the direction to turn off logging or to greatly reduce the logging.
```
Oct  7 06:16:55 raspberrypi lora_pkt_fwd[510]: WARNING: [gps] read() returned value 0
Oct  7 06:16:55 raspberrypi lora_pkt_fwd[510]: WARNING: [gps] read() returned value 0
Oct  7 06:16:55 raspberrypi lora_pkt_fwd[510]: WARNING: [gps] read() returned value 0
Oct  7 06:16:55 raspberrypi lora_pkt_fwd[510]: WARNING: [gps] read() returned value 0
Oct  7 06:16:55 raspberrypi lora_pkt_fwd[510]: WARNING: [gps] read() returned value 0
Oct  7 06:16:55 raspberrypi lora_pkt_fwd[510]: WARNING: [gps] read() returned value 0
Oct  7 06:16:55 raspberrypi lora_pkt_fwd[510]: WARNING: [gps] read() returned value 0
```

**Comment by cstratton** [comment]
Likely your best bet is to modify the source, or else filter it at the level of whatever you are using to run the packet forwarder as a service and get the output into a system log.
