### ISSUE TITLE
For 865MHz, what changes are required in global_conf.json

### ISSUE THREAD

**Issue by manishcse113** [Lora-net/packet_forwarder#139]
Global_conf.json is there with 905MHz, what changes are required for 865MHz configuration

**Comment by cstratton** [comment]
This would only be answerable in the context of particular bandplan, as the file is responsible for setting up the configuration of the front end radios and digital sub-IF's to exactly achieve the specific desired channels.

For some unofficial examples you could see https://github.com/TheThingsNetwork/gateway-conf

As the configuration file needs to match the way a particular board is wired to have the clock provided by one radio or the other, it could also make sense to seek a configuration file from the manufacturer or whatever specific board you are using, even if you use this repo for the software in general.
