### ISSUE TITLE
Whitelist from gateway to repeater

### ISSUE THREAD

**Issue by Francisco1306** [Lora-net/packet_forwarder#140]
Hello there,

I have a pygate with LoPy as a repeater and a a gateway. The gateway has a device's list and ai want to send periodically this list to repeater. 
Is that possible? Any sugestion on how to do it?

**Comment by cstratton** [comment]
The system you are referring to probably does not use this version of this software, but rather something heavily customized by the vendor.

>The gateway has a device's list 

This software has no such list, nor would any ordinary LoRaWAN gateway maintain one.  Gateways have no knowledge of who they are talking to, they only grant the servers which do have such knowledge quite raw low level access to the airwaves.
