### ISSUE TITLE
does class c supports otaaa

### ISSUE THREAD

**Issue by manivalaguru** [Lora-net/packet_forwarder#142]
hello,
i am using esp32 with sx1276 i can able to work with class in abp but could not able to do the same with otaa i want to know that class c supports otaa or not?
thanks and regards
manikandan v

**Comment by mcoracin** [comment]
Wrong project for you question I guess. 
I think it is rather a question for the LoRaWAN stack you are using, whichever it is. The gateway is quite agnostic from the LoRaWAN protocol, apart from timing constraints.
