### ISSUE TITLE
Error message !?

### ISSUE THREAD

**Issue by TheStudent227** [Lora-net/packet_forwarder#147]
Getting such a message after sending Join-Accept message.

{"stat":{"ackr":100.000000,"dwnb":1,"rxfw":1,"rxnb":1,"rxok":1,"time":"2021-12-13 16:11:56 GMT","txnb":0}}

Is it error ? What does this mean ?

**Comment by tobias-becker-vivavis** [comment]
This seems to be just a "stat" packet that contains just some statistical information for the server. See the gateway-to-network-server-protocol for further information an the meaning of the keys:
https://github.com/Lora-net/picoGW_packet_forwarder/blob/master/PROTOCOL.TXT

**Comment by TheStudent227** [comment]
Thank you for answer
