### ISSUE TITLE
Packet forwarder is rejecting packets with RF power not in LUT

### ISSUE THREAD

**Issue by reissjason** [Lora-net/packet_forwarder#21]
If a packet with RF power not found in the LUT is sent to the packet forwarder it is rejected.
Even though the loragw code will interpolate to the correct supported value.

**Comment by mcoracin** [comment]
Yes, it is a sanity check that has been added to highlight a misalignment between the network server and the gateway configuration.
An error message is sent back to the NS (JIT_ERROR_TX_POWER).

If you prefer your gateway not to check this, you can remove the test.
