### ISSUE TITLE
Simple Go client for the packet forwarder

### ISSUE THREAD

**Issue by niondir** [Lora-net/packet_forwarder#22]
I wrote this little client to connect to the Packet Forwarder via UDP in Go: https://github.com/Lobaro/lora-packet-forwarder-client

It's based on the TheThingsNetwork Bridge code from @brocaar - https://github.com/brocaar/lora-gateway-bridge

I used it to debug my packet forwarder but it can be used in any Go program that like to talk to the packet forwarder via UDP.

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support?__hstc=212684107.579a13689e43099691e328c9248e6ecc.1623103335314.1624470656297.1624635514661.6&__hssc=212684107.6.1624635514661&__hsfp=4176385453] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
