### ISSUE TITLE
radio_1 cannot be disabled

### ISSUE THREAD

**Issue by reissjason** [Lora-net/packet_forwarder#24]
The lgw_rxrf_setconf call for radio_1 will fail and cause the packet forwarder to crash if radio_1 is set to disabled.

INFO: radio 1 disabled
ERROR: NOT A VALID RADIO TYPE
ERROR: invalid configuration for radio 1

**Comment by mcoracin** [comment]
The packet forwarder does not crash but exits with an error, which is expected.
On Semtech's reference designs, the radio one is used as the clock source for the SX1301 (see the clksrc field in global_conf.json file).
So the concentrator cannot work with radio_1 disabled, hence the error message.
