### ISSUE TITLE
E286 fails spectral mask in Europe

### ISSUE THREAD

**Issue by BWhitten** [Lora-net/packet_forwarder#26]
We have found that at 23dBm and above the E286 card fails the spectral mask in Europe.
On a phone call with Semtech we brought this issue up and it was confirmed that these entries should be removed from the LUT.
https://github.com/Lora-net/packet_forwarder/blob/master/lora_pkt_fwd/cfg/global_conf.json.PCB_E286.EU868.basic#L174

Best double check the these reference settings.

**Comment by mcoracin** [comment]
Hello,

You're right, we'll remove the entries above 20dBm from the LUT for the E286 board.
The E336 board is there to solve the issue, adding a an FPGA with a notch filter inside.

Thanks
