### ISSUE TITLE
NetID missing from Beacon

### ISSUE THREAD

**Issue by gotthardp** [Lora-net/packet_forwarder#30]
I feel the implementation is not standard compliant. See
https://github.com/Lora-net/packet_forwarder/blob/master/lora_pkt_fwd/src/lora_pkt_fwd.c#L1873

The code says:
```
    /* fixed bacon fields (little endian) */
    beacon_pkt.payload[0] = 0x0; /* RFU */
    beacon_pkt.payload[1] = 0x0; /* RFU */
    /* 2-5 : time (variable) */
    /* 6-7 : crc1 (variable) */
```

Whereas the standard says the (US 902-928MHz) beacon frame content is

 3 | 4 | 2 | 7 | 1 | 2
---|---|---|---|---|---
NetID | Time | CRC | GwSpecific | RFU | CRC

The two-byte RFU feels wrong. Doesn't it? It should be 3-byte and it should be NetID, right?

**Comment by mcoracin** [comment]
The beacon implementation complies with LoRaWAN 1.0.2/1.1, in which NetID doesn't exist anymore.
The beacons are the same for every network now.
