### ISSUE TITLE
A lot of CRC_FAIL

### ISSUE THREAD

**Issue by akm-barnaul** [Lora-net/packet_forwarder#32]
Hello!
I'm using:
- iC880A (USB, with additional power supply) with a Cubieboard A20 (Ubuntu server)
- lora_gateway 3.10 (I know that is not the recent version, but I have only the USB-version of iC880A)
- packet_forwarder 2.10
Gateway is 2 m far from a node (Arduino + HopeRF 95).
A lot of packets are failed to forward because of CRC_FAIL error. thethingsnetwork.org application data log skips 1 or 2, or even 3 packets (according to counter).
Also, when I use a debug build of libloragw I see a lot of failed packets (third byte is 7).

So, the question is: how can I get rid of CRC_FAILED?

**Comment by johanstokking** [comment]
This is almost always an RF issue. Check antennas and wiring. Also it might be slight differences between the frequencies. Note also that SF11 and SF12 have known problems in older versions that cause CRC errors.

**Comment by mcoracin** [comment]
Just in case, check that the 'lorawan_public' field of the global_conf.json file is set to true. It should be the case by default.
And of course ensure that the corresponding configuration is done on the Hope RF side (public/private).
When there is a mismatch we get only around 10% of the packets.

**Comment by akm-barnaul** [comment]
> Just in case, check that the 'lorawan_public' field of the global_conf.json file is set to true. It should be the case by default.
And of course ensure that the corresponding configuration is done on the Hope RF side (public/private).

Checked the fields - they are set as you said

> When there is a mismatch we get only around 10% of the packets.

I get about 90% of the packets.

iC880A manufacturer advised me to reduce transmit power of my node (arduino + LMIC library + hoperf 95w), but playing with LMIC_setDrTxpow() had no effect.

**Comment by akm-barnaul** [comment]
> This is almost always an RF issue. Check antennas and wiring. Also it might be slight differences between the frequencies. Note also that SF11 and SF12 have known problems in older versions that cause CRC errors.

Wiring is ok, I have about 10% of packets lost. 
Gateway and node use the same frequencies and SF7:
"frequency": 868.92,
  "modulation": "LORA",
  "data_rate": "SF7BW125",
  "coding_rate": "4/5",
  "gateways": [
    {
      "gtw_id": "eui-02d609fffe80c5cb",
      "timestamp": 1336239307,
      "time": "2017-03-10T02:46:05.125464Z",
      "channel": 4,
      "rssi": -42,
      "snr": 9
    }
  ],

**Comment by lancezhangsf** [comment]
HI，akm-barnaul
     I have the same problem,  i set freq 470Mhz,  the gateway have a lot of crc error , the data was given up . i set sf=11,bw=125K,then the freq = 471.5, I have about 10% of packets lost.  But when the node from 470 to 489,the gw show a lot crc errors.

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support?__hstc=212684107.579a13689e43099691e328c9248e6ecc.1623103335314.1624470656297.1624635514661.6&__hssc=212684107.6.1624635514661&__hsfp=4176385453] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
