### ISSUE TITLE
Extra information

### ISSUE THREAD

**Issue by VKhudyakov25** [Lora-net/packet_forwarder#33]
Hello, I have some questions:
1. The RF packet from end device encoded using Base64. What type of information we can get, decoding metadata as field "data".
2. How we can get detailed information about gateway and endpoint (battery level, temperature and etc.)

**Comment by mcoracin** [comment]
Hello,
The information contained in the "data" field are application dependent.
The gateway plays no role in that, it just forward the data received "as is" and add radio metadata like signal strength etc... on top of it.
