### ISSUE TITLE
Where I can get LoRaWAN v1.1?

### ISSUE THREAD

**Issue by zhoubx123** [Lora-net/packet_forwarder#36]
Where I can get LoRaWAN v1.1? I just have LoRaWAN v1.0.2.

**Comment by a-andreyev** [comment]
I guess it is not connected directly to the `packet_forwarder` repository and you could ask for it [here](https://www.lora-alliance.org/Contact/Request-Specification-Form). But looks like v1.1 is not available yet.

**Comment by mcoracin** [comment]
Yes, v1.1 is not available yet. But as far as beaconing is concerned v1.0.2 and v1.1 are the same. That's why the latest release mention v1.1.
