### ISSUE TITLE
Packet forwarder with SX127X

### ISSUE THREAD

**Issue by ethicstechOSS** [Lora-net/packet_forwarder#37]
Can I use packet forwarder with SX127X modem instead of multichannel SX130X modem?. My setup is RPI board with HopeRF SX1272 LoRa module. I dont have SX130X and not interested on multichannel as well. 

TIA,
Prakash

**Comment by mcoracin** [comment]
You can use it if you rewrite the HAL (lora_gateway) for the SX1272.

There are some initiatives for this on the internet, have a look to the The Things Network community.
