### ISSUE TITLE
Proxy config

### ISSUE THREAD

**Issue by camilorojasg** [Lora-net/packet_forwarder#41]
Hi. Is it possible to configure a proxy?

I've tried with `http_proxy` env variable, but it doesn't work.

**Comment by temporaryaccount** [comment]
packet_forwarder uses UDP sockets for communication, so it is not possible to configure a standard HTTP (or SOCKS) proxy which works only with TCP sockets. I would suggest you to use a VPN like OpenVPN instead of proxy, all your traffic will be authenticated and encrypted too.
