### ISSUE TITLE
packets types

### ISSUE THREAD

**Issue by akieni** [Lora-net/packet_forwarder#51]
Hi, I have a question about how this project can help us with a loranet deployment.. 
We would like to forward mysql data through lora (From lora gateway to lora device and vice versa) and I wonder if this lora-net packet forwarder can work in that scenario

________                                                                                    ____________         ____________
| Server 2 |------|Lora device    |*********** radio link**************** |Lora Gateway  |------| Mysql serve1|
| mysql     |        |___________|                                                  |____________|        |___________|

**Comment by mcoracin** [comment]
You can transport any kind of data in the packet payload.
