### ISSUE TITLE
Unable to find logs of DOWNLINK queue

### ISSUE THREAD

**Issue by VikhyatChandra** [Lora-net/packet_forwarder#53]
Hi,
I need your assist on Something, We have made the api call to push the packet from the server side. We are  also Recieving 200 status (OK). But we would like to see where we are recieving the packet. Is there a log file which is generated at the gateway end?.

**Comment by mcoracin** [comment]
If you are using this packet forwarder, there is no log handled by it.
But you can stop the packet forwarder running in background, and run it from the console.

You'll see uplink and downlink logs.

Like this:
```
JSON up: {"rxpk":[{"tmst":2990387474,"chan":9,"rfch":1,"freq":868.800000,"stat":1,"modu":"FSK","datr":50000,"rssi":-33,"size":29,"data":"gK8BzAAAzQgCMP+xMGzoiSGWptZXe6CK/dnE6Mc="}]}
INFO: [up] PUSH_ACK received in 12 ms
INFO: [down] PULL_RESP received  - token[227:231] :)

JSON down: {"txpk":{"tmst":2991387474,"freq":868.8,"powe":14,"rfch":0,"modu":"FSK","ncrc":false,"ipol":false,"datr":50000,"fdev":25000,"size":13,"data":"YK8BzAAgAAABmjJuDQ=="}}
INFO: [down] PULL_ACK received in 0 ms
```
