### ISSUE TITLE
How can I reset 1301 timestamp counter?

### ISSUE THREAD

**Issue by ChunChiehKung** [Lora-net/packet_forwarder#57]
Hi Sir,

I have two 1301 AP modules on my board.
There are two packet_forwarder process running in the mean while.
However, I don't have GPS to correct the time clock of 1301 timestamp periodically.
So that, the timestamp difference of these two packet_forwarder from 1301 is  getting longer.
Can I reset the 1301 timestamp periodically?
Or there any method I can sync the timestamp of each 1301?
Please advise.
Thanks.

**Comment by mcoracin** [comment]
Hello,

Why do you want to keep both 1301 counter in sync? :)
