### ISSUE TITLE
installing

### ISSUE THREAD

**Issue by alexanderplanar** [Lora-net/packet_forwarder#66]
Hello!

I use the packet_forwarder on the BeagleBone computer, and have to run the application each time I power it on. Is there way to "install" the packet forwarder as system service via the packet manger, like "aptitude install packet-forwarder" ? What repository should I use?

Thanks in advance,
Best regards!

**Comment by mcoracin** [comment]
You can use a cron job to do this, or a define an autostart service, but the way to do it depens on the linux distribution you are using.

I'll close this issue, because it is not directly related to the packet forwarder functionnality.
