### ISSUE TITLE
Packet forwarder discards PULL_RESP messages from server after downlink transmissions.

### ISSUE THREAD

**Issue by maxpesce** [Lora-net/packet_forwarder#68]
Hello, we found a strange behvior in the packet forwarder. After sending three downlink messages in "immediate" mode, we got some errors regarding the JIT queue of the packet forwarder. It seems that the gateway rejects the PULL_RESP packet because of wrong timestamp. Does anybody know what's going on?
Below the packet forwarder log.

Thanks in advance!

Nov 08 18:20:50 beaglebone start_pkt_fwd.sh[1260]: INFO: [up] PUSH_ACK received in 28 ms
Nov 08 18:20:50 beaglebone start_pkt_fwd.sh[1260]: INFO: [down] PULL_ACK received in 3 ms
Nov 08 18:20:50 beaglebone start_pkt_fwd.sh[1260]: INFO: [down] PULL_RESP received  - token[0:0] :)
Nov 08 18:20:50 beaglebone start_pkt_fwd.sh[1260]: JSON down: {"txpk":{"imme":true,"freq":869.525,"rfch":0,"powe":14,"modu":"LORA","datr":"SF12BW125","codr":"4/5","ipol":true,"size":28,"data":"oM6O4wYAwwECDa0Sl6Hx8f8zjiACNQBbdz1dzw=="}}
Nov 08 18:20:50 beaglebone start_pkt_fwd.sh[1260]: INFO: [down] a packet will be sent in "immediate" mode
Nov 08 18:20:50 beaglebone start_pkt_fwd.sh[1260]: INFO: [down] PULL_RESP received  - token[0:0] :)
Nov 08 18:20:50 beaglebone start_pkt_fwd.sh[1260]: JSON down: {"txpk":{"imme":true,"freq":869.525,"rfch":0,"powe":14,"modu":"LORA","datr":"SF12BW125","codr":"4/5","ipol":true,"size":28,"data":"oFB49gYAoAACLW+DmaeRjf6bS261nNf/gYqg7Q=="}}
Nov 08 18:20:50 beaglebone start_pkt_fwd.sh[1260]: INFO: [down] a packet will be sent in "immediate" mode
Nov 08 18:20:50 beaglebone start_pkt_fwd.sh[1260]: INFO: [down] PULL_RESP received  - token[0:0] :)
Nov 08 18:20:50 beaglebone start_pkt_fwd.sh[1260]: JSON down: {"txpk":{"imme":true,"freq":869.525,"rfch":0,"powe":14,"modu":"LORA","datr":"SF12BW125","codr":"4/5","ipol":true,"size":28,"data":"oIW4wAcAvwECWTBDlfYvndMo081io8NNr+Gmtg=="}}
Nov 08 18:20:50 beaglebone start_pkt_fwd.sh[1260]: INFO: [down] a packet will be sent in "immediate" mode
Nov 08 18:20:50 beaglebone start_pkt_fwd.sh[1260]: INFO: tx_start_delay=1495 (1495.500000) - (1497, bw_delay=1.500000, notch_delay=0.000000)
Nov 08 18:20:50 beaglebone start_pkt_fwd.sh[1260]: INFO: tx_start_delay=1495 (1495.500000) - (1497, bw_delay=1.500000, notch_delay=0.000000)
Nov 08 18:20:50 beaglebone start_pkt_fwd.sh[1260]: INFO: tx_start_delay=1495 (1495.500000) - (1497, bw_delay=1.500000, notch_delay=0.000000)
Nov 08 18:20:50 beaglebone start_pkt_fwd.sh[1260]: INFO: [down] PULL_ACK received in 15 ms
Nov 08 18:20:50 beaglebone start_pkt_fwd.sh[1260]: INFO: Received pkt from mote: 07C0B885 (fcnt=0)
Nov 08 18:20:50 beaglebone start_pkt_fwd.sh[1260]: JSON up: {"rxpk":[{"tmst":3498167420,"chan":2,"rfch":1,"freq":868.500000,"stat":1,"modu":"LORA","datr":"SF9BW125","codr":"4/5","lsnr":7.8,"rssi":-45,"size":13,"data":"QIW4wAeAAAABx1gZPw=="}]}
Nov 08 18:20:50 beaglebone start_pkt_fwd.sh[1260]: INFO: [up] PUSH_ACK received in 18 ms
Nov 08 18:20:50 beaglebone start_pkt_fwd.sh[1260]: INFO: [down] PULL_RESP received  - token[0:0] :)
Nov 08 18:20:50 beaglebone start_pkt_fwd.sh[1260]: JSON down: {"txpk":{"imme":false,"tmst":3499167420,"freq":868.5,"rfch":0,"powe":14,"modu":"LORA","datr":"SF9BW125","codr":"4/5","ipol":true,"size":28,"data":"oIW4wAcAwAECoSDYm9UyN77IL0wHEhwc2ogkIw=="}}
Nov 08 18:21:34 beaglebone start_pkt_fwd.sh[1260]: src/jitqueue.c:251:jit_enqueue(): ERROR: Packet REJECTED, timestamp seems wrong, too much in advance (current=3499634555, packet=3499167420, type=0)
Nov 08 18:21:34 beaglebone start_pkt_fwd.sh[1260]: ERROR: Packet REJECTED (jit error=2)
Nov 08 18:21:34 beaglebone start_pkt_fwd.sh[1260]: INFO: [down] PULL_ACK received in 53 ms
Nov 08 18:21:34 beaglebone start_pkt_fwd.sh[1260]: INFO: Received pkt from mote: 06E38ECE (fcnt=10)
Nov 08 18:21:34 beaglebone start_pkt_fwd.sh[1260]: JSON up: {"rxpk":[{"tmst":3510970404,"chan":0,"rfch":1,"freq":868.100000,"stat":1,"modu":"LORA","datr":"SF9BW125","codr":"4/5","lsnr":11.5,"rssi":-47,"size":39,"data":"QM6O4waACgACJZl1kmlt+yBEdHQ975Pg8DWeDpiFityPuR8BHOdk"}]}
Nov 08 18:21:34 beaglebone start_pkt_fwd.sh[1260]: INFO: [up] PUSH_ACK received in 39 ms
Nov 08 18:21:34 beaglebone start_pkt_fwd.sh[1260]: INFO: [down] PULL_RESP received  - token[0:0] :)
Nov 08 18:21:34 beaglebone start_pkt_fwd.sh[1260]: JSON down: {"txpk":{"imme":false,"tmst":3511970404,"freq":868.1,"rfch":0,"powe":14,"modu":"LORA","datr":"SF9BW125","codr":"4/5","ipol":true,"size":28,"data":"oM6O4wYAxAECYAxiTkQT6eV/EKP98zRF0rOdwQ=="}}
Nov 08 18:21:34 beaglebone start_pkt_fwd.sh[1260]: src/jitqueue.c:251:jit_enqueue(): ERROR: Packet REJECTED, timestamp seems wrong, too much in advance (current=3512265351, packet=3511970404, type=0)
Nov 08 18:21:34 beaglebone start_pkt_fwd.sh[1260]: ERROR: Packet REJECTED (jit error=2)

**Comment by cstratton** [comment]
You appear to be trying to reply to an uplink packet ending at 3510970404 with a downlink packet starting at 3511970404 - precisely one second later such as typical for a LoRaWAN RX1.

However it would appear that the downlink packet is reaching the gateway about 295 milliseconds after it was supposed to transmit, when in reality it probably needs to get there (as a guess) at least 60 milliseconds in advance.  That typically indicates either a slow backhaul network or perhaps in extreme cases a slow computer running the packet forwarder.

Because the gateway microsecond counter wraps at 32 bits, it sees a packet that is actually "late" as being almost a full wrapping time "early" and prints an error message that is almost opposite from the actual situation.

Your attempts to transmit "immediate" packets would work because the gateway just sends those as soon as they can - though they don't really work for LoRaWAN RX windows.
