### ISSUE TITLE
Confirmed Uplink: ACK miss

### ISSUE THREAD

**Issue by alexanderplanar** [Lora-net/packet_forwarder#72]
Hello, 
I assembled the LoRa system on my table.
LoRa Server and Application Server is running under VirtualBox on my PC.
My gateway is based on BeagleBone Black board and Microchip's Radio Board (without FPGA).

I use confirmed uplink message, and I noticed that gateway does not emit ACK packet sometimes.
Tcpdump on the gateway (BeagleBone, BBB) shows that the packet is received by the network subsystem.
But the Node does receive nothing. Then I decided to ensure that the packet is not emitted.
I spy on the radio path using SDR Tuner, and confirm that the packet is not emitted by gateway, however tcpdump logs that the packet has been received (BBB).
To syncronise the time on all network nodes (server, gateway, SDR) the NTP is used, so I can determine whether the packet has been emitted or not.
So, End Node trys to retransmit the message, however the server already confirmed the message and does not respond. So, End node has no chances to receive ACK message and must consider the message undelivered.
I made number of tests and found out that sometimes the device receive the ACK message but it is corrupted, however SDR Tuner does not register any noise on the channel, the distance btw the Node and the Gateway is about 2 meters. I do not understand how the message can be currupted in such conditions.
The bug is unstable and appears time to time, I do find out no external triggers to cause the bug.

P.S. The uplink messages is delivered with no problems to server.

Does anyone face to this problem?

**Comment by alexanderplanar** [comment]
**UPD.**
I catched the packet forwarder error message:

> JSON down: {"txpk":{"imme":false,"tmst":256928027,"freq":868.3,"rfch":0,"powe":14,"modu":"LORA","datr":"SF7BW125","codr":"4/5","ipol":true,"size":12,"data":"YPwKEgegOQDEMNh9"}}
> src/jitqueue.c:251:jit_enqueue(): ERROR: Packet REJECTED, timestamp seems wrong, too much in advance (current=258209393, packet=256928027, type=0)
> ERROR: Packet REJECTED (jit error=2)
> lgw_receive:1155: FIFO content: 1 83 2 5 1d

It appears at the moment of receiving the ACK from server and causing not transmitting the ACK packet.

As I understand, the server responds too late?

**Comment by alexanderplanar** [comment]
I installed LoRa Gateway Bridge on the gateway host, and subscribe to mqtt-topic "gateway/#"
When the the bug appears (missing ACK packet), the error has been reported: "gateway/aa555a0000000101/ack {"mac":"aa555a0000000101","token":0,"error":"TOO_EARLY"}"

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support?__hstc=212684107.579a13689e43099691e328c9248e6ecc.1623103335314.1624470656297.1624635514661.6&__hssc=212684107.6.1624635514661&__hsfp=4176385453] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
