### ISSUE TITLE
JSON string length is difficult to determine

### ISSUE THREAD

**Issue by huntc** [Lora-net/packet_forwarder#78]
I found the protocol difficult to implement given that associated JSON data provides no means having its length determined i.e. either through having a one-byte size field as per Pascal strings, or a zero byte terminator as per C strings. Instead, the receive buffer bytes must be read and the JSON braces counted in order to determine the end.

I believe that the assumption is that a receive buffer will contain the packet to be parsed in its entirety as per #77.

**Comment by johanstokking** [comment]
Use a proper JSON deserializer, i.e. Parson for C or any builtin parser in frameworks.

**Comment by huntc** [comment]
My observation is that the protocol is more difficult to deal with than it needs to be. As an enhancement suggestion, having a length byte or delimiter would make it much easier to deal with. Thanks.

**Comment by johanstokking** [comment]
You are basically stating that JSON is harder to deal with than CSV. That's correct. I don't know how that relates to this protocol.

**Comment by huntc** [comment]
Having a length byte as the first byte of a stream let’s you know in advance of how many other bytes are coming. When you call recv, you will not know at that point if you have read all of the bytes required in the absence of a length byte. 

Alternatively, having a delimeter allows you to call recv until that delimiter is returned. 

The current protocol declares a root level `}` as the delimeter. However, determining this is more difficult that having either a length byte or a zero byte delimeter.

**Comment by huntc** [comment]
What’s the rationale for closing?

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support?__hstc=212684107.579a13689e43099691e328c9248e6ecc.1623103335314.1624470656297.1624635514661.6&__hssc=212684107.6.1624635514661&__hsfp=4176385453] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
