### ISSUE TITLE
LoRaWAN Gateway as a Repeater

### ISSUE THREAD

**Issue by KhaledAljehani** [Lora-net/packet_forwarder#80]
Hi,

How can I configure the gateway (packets forwarder) to work as a repeater?

Nodes transmit packets and gateway receive them, then the gateway forwards/transmits the packets to another gateway, until it reaches its destination.

The purpose is to cover an area with LoRaWAN network without Internet connectivity.

Best regards.

**Comment by x893** [comment]
You can't configure current version as repeater.
You need create custon software.

**Comment by KhaledAljehani** [comment]
I really appreciate your reply.

The custom software will be based on packet forwarder or LoRa gateway only?

Best regards.

**Comment by x893** [comment]
You use packet forwarder codes for receive and transmite LORA packets.
But need create codes for routing packets to/from other gateway (now use UDP linux sockets).

**Comment by KhaledAljehani** [comment]
Thanks for your help.

I will try to develop a code for adding repeater function.

**Comment by Asghar-Usman** [comment]
Hi @KhaledAljehani  

did you manage to set up the repeater functionality in gateways? 
I am wondering about a similar scenario and would be great if  you could share your experience or progress.

**Comment by KhaledAljehani** [comment]
Hi @berba9 

Yes, I did a simple repeater that receives packets from nodes, then sets TX parameters and transmit the received packet to another repeater / gateway. The implementation supports only uplinks.

Also, the development was in the packet forwarder, it will be very easy if you did a good analysis.

Let me know if you have questions.

Best regards.

**Comment by Asghar-Usman** [comment]
Hi @KhaledAljehani thanks for your response. 
Is it possible that the gateways communicate with each other at regular intervals to synchronize their clocks (some sort of time synchronization protocol). As far as i understood from a brief look at the source code(lorapacket forwarder), the gps 1pps signal is used to synchronize the internal clock of the gateways. This internal clock is then used to provide raw timestamps ("tmst") and wall clock time ("time"). This is good but not very precise (jitters). Thats why i am wondering if some time synchronization protocol could be implemented, where gateways exchange information to synchronize clocks.
Best Regards :)

**Comment by KhaledAljehani** [comment]
@berba9 
Sorry for replaying late.

To honest, I did not reach this level but I can assure that exchanging data between gateways is applicable.

**Comment by gnob417** [comment]
Hi @KhaledAljehani .
I'm curious about whether repeater role for downlinks is possible or not.
it seems a gateway couldn't receive downlink from another gateway when i tested.

**Comment by mcoracin** [comment]
@gnob417 be careful with the signal polarity you set when sending a LoRa packet from a gateway to another.
In LoRaWAN, there is an inverted polarity between uplinks and downlinks. So basically, when a Gateway sends a downlink to a device it configures the TX as "ipol=true", to match the device configuration for receiving downlinks.
But if you want to send a packet to another gateway, which expects a non-inverted polarity, you need to configure you TX accordingly. Please check the "ipol" parameter usage in the packet forwarder.

**Comment by slarun** [comment]
Hi @KhaledAljehani, have you faced looping issue in the repeater? Meaning the packet transmitted by repeated again received by the repeater and got into loop. How you avoided it?

Thanks

**Comment by rohitkumar5293** [comment]
Hi @KhaledAljehani ,

"Yes, I did a simple repeater that receives packets from nodes, then sets TX parameters and transmit the received packet to another repeater / gateway. The implementation supports only uplinks."

Will you please share us how you have implemented gateway as a repeater only for uplink? It would be great if you share us your code. I tried to set TX parameter and transmitting the packet but its remain unsuccessful.

**Comment by lfo212** [comment]
Hi, i’ve been developing a solution for this, it’s a laboratory experiment for now.

i’m using a gateway made with a raspberry pi 3 and a rak831 concentrator.

The idea is to use a gateway with no internet connection to repeat the messages received in a frequency pool.

I modify the packet forwarder program running in the raspberry. This program has five threads that work in five different tasks and use a loragw library to communicate with the concentrator. I leave only one thread: the one that receives the lora packets and modify it to resend the packet in other frecuency pool, used by the gateways.

About downlinks; it's something that i'm working on.

**Comment by lfo212** [comment]
Two teories. send an ACK from the repetear and no confirmation from the gateway to the repeater, that means, from user. Or sending the ACK from the gateway hoping it arrived to the endnode working with RX windows

**Comment by crabsun** [comment]
> Thanks for your help.
> 
> I will try to develop a code for adding repeater function.

Hi,
any update on LoRaWAN gateway as a repeater implementation?

**Comment by nestorayuso** [comment]
I think the support for repeaters in LoRaWAN will be removed in v1.0.4

**Comment by AbhishekLakhara0209** [comment]
Hi @luchostem ,

Have finished done the changes for the downlink?

Are you able  to receive the join accept from the repeater gateway?
