### ISSUE TITLE
packet_forwarder ignores unconfirmed UPLINK messages

### ISSUE THREAD

**Issue by Almaz1c** [Lora-net/packet_forwarder#82]
Hi!
After successfully provided JOIN procedure by `packet_forwarder/lora_pkt_fwd`:
```
INFO: Disabling GPS mode for concentrator's counter...
INFO: host/sx1301 time offset=(1520789735s:345101µs) - drift=1945373645µs
INFO: Enabling GPS mode for concentrator's counter.

INFO: [down] PULL_ACK received in 1 ms

INFO: Received pkt from mote: 00000000 (fcnt=0)

JSON up: {"rxpk":[{"tmst":3749387,"chan":0,"rfch":1,"freq":868.100000,"stat":1,"modu":"LORA","datr":"SF7BW125","codr":"4/5","lsnr":9.2,"rssi":-71,"size":23,"data":"AAAAAAAAAAAAD343bzM4MTYPIK+tm+w="}]}
INFO: [up] PUSH_ACK received in 2 ms
INFO: [down] PULL_RESP received  - token[114:189] :)

JSON down: {"txpk":{"imme":false,"tmst":8749387,"freq":868.1,"rfch":0,"powe":14,"modu":"LORA","datr":"SF7BW125","codr":"4/5","ipol":true,"size":17,"data":"IJ7VlZIZU0QLOSUziI3BQ5M=","brd":0,"ant":0}}
INFO: tx_start_delay=1495 (1495.500000) - (1497, bw_delay=1.500000, notch_delay=0.000000)
INFO: [down] PULL_ACK received in 1 ms
INFO: [down] PULL_ACK received in 4 ms

##### 2018-03-11 17:36:07 GMT #####
### [UPSTREAM] ###
# RF packets received by concentrator: 29
# CRC_OK: 3.45%, CRC_FAIL: 96.55%, NO_CRC: 0.00%
# RF packets forwarded: 1 (23 bytes)
# PUSH_DATA datagrams sent: 1 (203 bytes)
# PUSH_DATA acknowledged: 100.00%
### [DOWNSTREAM] ###
# PULL_DATA sent: 3 (100.00% acknowledged)
# PULL_RESP(onse) datagrams received: 1 (191 bytes)
# RF packets sent to concentrator: 1 (17 bytes)
# TX errors: 0
# TX rejected (collision packet): 0.00% (req:1, rej:0)
# TX rejected (collision beacon): 0.00% (req:1, rej:0)
# TX rejected (too late): 0.00% (req:1, rej:0)
# TX rejected (too early): 0.00% (req:1, rej:0)
# BEACON queued: 0
# BEACON sent so far: 0
# BEACON rejected: 0
### [JIT] ###
# SX1301 time (PPS): 2409221
src/jitqueue.c:448:jit_print_queue(): INFO: [jit] queue is empty
### [GPS] ###
# GPS sync is disabled
##### END #####

JSON up: {"stat":{"time":"2018-03-11 17:36:07 GMT","rxnb":29,"rxok":1,"rxfw":1,"ackr":100.0,"dwnb":1,"txnb":1}}
INFO: [up] PUSH_ACK received in 1 ms
INFO: [down] PULL_ACK received in 1 ms
```
it ignores UPLINK unconfirmed messages from recently JOINED device at all. I don't see any JSON up messages about "rxpk" but only "stat" messages.
I am pretty sure that there are unconfirmed messages are exist - I can see them using 'lora_gateway/util_pkt_logger':
```
"AA555A0000000101","","2018-03-11 17:47:42.576Z",  72068748, 868500000,1, 2,"CRC_OK" , 29,"LORA",125000,"SF12"  ,"4/5",-68, +7.5,"404B66FC-07808E00-02BEBD9B-166698E6-E4CA2649-21050B4A-BC135B7B-CA"
"AA555A0000000101","","2018-03-11 17:47:48.521Z",  78011900, 868100000,1, 0,"CRC_OK" , 29,"LORA",125000,"SF12"  ,"4/5",-70,+10.2,"404B66FC-07808F00-029241AD-B39875CC-7C4433B6-C5B89831-A9B44852-2E"
"AA555A0000000101","","2018-03-11 17:47:54.345Z",  83836060, 867700000,0, 6,"CRC_OK" , 29,"LORA",125000,"SF12"  ,"4/5",-71,+11.2,"404B66FC-07809000-02D1D9BC-7F4A2701-040D18AF-12682BA0-07EABACC-0D"
"AA555A0000000101","","2018-03-11 17:48:04.613Z",  94105364, 868500000,1, 2,"CRC_OK" , 29,"LORA",125000,"SF12"  ,"4/5",-70, +7.8,"404B66FC-07809200-02F74286-51B95825-D3B7C08D-B1EFB3DB-F0DDC8A2-C9"
"AA555A0000000101","","2018-03-11 17:48:08.766Z",  98257484, 868100000,1, 0,"CRC_OK" , 29,"LORA",125000,"SF12"  ,"4/5",-70,+10.0,"404B66FC-07809300-026859EC-92190992-2E726F86-E6191DDA-D8493FA8-37"
"AA555A0000000101","","2018-03-11 17:48:12.792Z", 102284052, 867500000,0, 5,"CRC_OK" , 29,"LORA",125000,"SF12"  ,"4/5",-72, +6.8,"404B66FC-07809400-02B0EFEB-E0246961-1B3F9041-2EF6B913-7993D944-E4"
```
Here I turned off `LORAWAN_DUTYCYCLE_ON` for debugging purposes on my node to send RF packets every 5 seconds. No matter turned it ON or OFF, - it doesn't matter - `packet_forwarder` not forward packets. Tried to wait for 30 minutes - no any packet forwarded.
If I restart `packet_forwarder` I see only one "rxpk" but not every time I restart it.
E.g. it forwards only first package (JOIN request or Unconfirmed message after restart) 
Is there any `LORAWAN_DUTYCYCLE_ON` like config exist on `packet_forwarder` to prevent "rxpk" forwarding too often or something else? How can I turn it off for debugging purposes?

**Comment by mcoracin** [comment]
Hello,

It seems that your gateway receives packets, but with CRC errors mostly:
```
# RF packets received by concentrator: 29
# CRC_OK: 3.45%, CRC_FAIL: 96.55%, NO_CRC: 0.00%
```

Do you have both the gateway and the devices configured with the same syncword (public/private)?
In the gateway, the configuration is 
```
lorawan_public:true
```
Which gateway is it?

You can also add the DEBUG_HAL flag to 1 in library.cfg file of lora_gateway project, to have more info on what is going-on.

**Comment by Almaz1c** [comment]
My gateway receives packets with CRC_FAIL from third-party LoRaWAN networks. That is why I disabled DEBUG_HAL flag to hide packets that did not send by my node. I am pretty sure that packets emitted by my node are received by the gateway with CRC_OK status.
Should I try to change `lorawan_public` to `false` in `global_conf.json` ?
Can you point me to similar config flag in `LoRaMac-node` ?
Now gateway forwards only first received packet (JOIN request on startup or Unconfirmed message after restart).

**Comment by mcoracin** [comment]
The similar config in LoRaMac-node is LORAWAN_PUBLIC_NETWORK, in the Commissioning.h file.
It has to be aligned with the gateway 'lorawan_public' setting.

**Comment by Almaz1c** [comment]
Both gateway and node configured as **public**.
Here is sequencing:
1. lora-gateway-bridge started
2. lora node started
3. **JOIN** request forwarded. Following **UnconfirmedDataUp** messages not forwarded.
4. lora-gateway-bridge restarted.
5. First **UnconfirmedDataUp** forwarded. Following **UnconfirmedDataUp** messages not forwarded.
It forwards **UnconfirmedDataUp** not after every restart.

**Comment by Almaz1c** [comment]
When I replaced SX1308 based LoRaGo Port dev board to SX1301 based iC880A all UnconfirmedMessageACKs started to be forwarded successfully.

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support?__hstc=212684107.579a13689e43099691e328c9248e6ecc.1623103335314.1624470656297.1624635514661.6&__hssc=212684107.6.1624635514661&__hsfp=4176385453] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
