### ISSUE TITLE
gateway log for "imme"

### ISSUE THREAD

**Issue by gnob417** [Lora-net/packet_forwarder#84]
Hi, i found strange situation.

when i request downlink packet emission with "imme" from server, my gateway packet forwarder log seems strange. it seems gw transmits packet and receives it at same time. (look at data part).
what's the problem of this situation?

> JSON down: {"txpk":{"powe":23,"imme":true,"codr":"4/5","datr":"SF12BW125","freq":923.1,"modu":"LORA","rfch":0,"ipol":true,"size":5,"data":"8AwmKPo="}}
> INFO: [down] a packet will be sent in "immediate" mode
> INFO: tx_start_delay=1495 (1495.500000) - (1497, bw_delay=1.500000, notch_delay=0.000000)
> 
> INFO: Received pkt from mote: FA28260C (fcnt=3787)
> 
> JSON up: {"rxpk":[{"tmst":108149068,"chan":4,"rfch":1,"freq":922.900000,"stat":1,"modu":"LORA","datr":"SF12BW125","codr":"4/5","lsnr":-2.5,"rssi":-109,"size":5,"data":"8AwmKPo="}]}
> INFO: [up] PUSH_ACK received in 0 ms

**Comment by mcoracin** [comment]
Which gateway are you using? Is it a full_duplex gateway?

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support?__hstc=212684107.579a13689e43099691e328c9248e6ecc.1623103335314.1624470656297.1624635514661.6&__hssc=212684107.6.1624635514661&__hsfp=4176385453] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
