### ISSUE TITLE
installing packet_forwarder on lora gateway 

### ISSUE THREAD

**Issue by ThomasUnivRennes1** [Lora-net/packet_forwarder#85]
Hi everybody, 

I have my own LoRa gateaway (witch is : **https://www.mouser.fr/new/semtech/semtech-iot-kits/** SX1301) and I try to install the packet_forwarder without success, I had the packet_forwarder directory (with my modification : gateway ID, server_address, server_port) in the directory /opt/lora-net/gateway on the gateway. 
I follow this instruction : https://github.com/Lora-net/packet_forwarder/wiki/Use-with-Raspberry-Pi, enable spi driver, Compile SX1301 driver/HAL and when I want to compile the packet_forwarder-master I have an error 2 ( see bellow )

lora@lora-iot-sk /opt/lora-net/gateway $ cd ./packet_forwarder-master
lora@lora-iot-sk /opt/lora-net/gateway/packet_forwarder-master $ make all
make all -e -C lora_pkt_fwd
make[1]: Entering directory '/opt/lora-net/gateway/packet_forwarder-master/lora_pkt_fwd'
gcc -c -O2 -Wall -Wextra -std=c99 -Iinc -I. -D VERSION_STRING="\"`cat ../VERSION`\"" -I../../lora_gateway/libloragw/inc src/lora_pkt_fwd.c -o obj/lora_pkt_fwd.o
src/lora_pkt_fwd.c: In function ‘parse_SX1301_configuration’:
src/lora_pkt_fwd.c:285:27: error: storage size of ‘lbtconf’ isn’t known
     struct lgw_conf_lbt_s lbtconf;
                           ^
src/lora_pkt_fwd.c:365:26: error: ‘LBT_CHANNEL_FREQ_NB’ undeclared (first use in this function)
                 if (i >= LBT_CHANNEL_FREQ_NB)
                          ^
src/lora_pkt_fwd.c:365:26: note: each undeclared identifier is reported only once for each function it appears in
src/lora_pkt_fwd.c:393:13: warning: implicit declaration of function ‘lgw_lbt_setconf’ [-Wimplicit-function-declaration]
             if (lgw_lbt_setconf(lbtconf) != LGW_HAL_SUCCESS) {
             ^
src/lora_pkt_fwd.c:524:27: error: ‘struct lgw_conf_rxrf_s’ has no member named ‘tx_notch_freq’
                     rfconf.tx_notch_freq = (uint32_t)json_object_dotget_number(conf_obj, param_name);
                           ^
In file included from src/lora_pkt_fwd.c:50:0:
src/lora_pkt_fwd.c:529:193: error: ‘struct lgw_conf_rxrf_s’ has no member named ‘tx_notch_freq’
             MSG("INFO: radio %i enabled (type %s), center frequency %u, RSSI offset %f, tx enabled %d, tx_notch_freq %u\n", i, str, rfconf.freq_hz, rfconf.rssi_offset, rfconf.tx_enable, rfconf.tx_notch_freq);
                                                                                                                                                                                                 ^
inc/trace.h:27:29: note: in definition of macro ‘MSG’
 #define MSG(args...) printf(args) /* message that is destined to the user */
                             ^
src/lora_pkt_fwd.c:285:27: warning: unused variable ‘lbtconf’ [-Wunused-variable]
     struct lgw_conf_lbt_s lbtconf;
                           ^
src/lora_pkt_fwd.c: In function ‘main’:
src/lora_pkt_fwd.c:1416:9: warning: implicit declaration of function ‘lgw_gps_disable’ [-Wimplicit-function-declaration]
         i = lgw_gps_disable(gps_tty_fd);
         ^
src/lora_pkt_fwd.c: In function ‘thread_up’:
src/lora_pkt_fwd.c:1625:17: warning: implicit declaration of function ‘lgw_cnt2gps’ [-Wimplicit-function-declaration]
                 j = lgw_cnt2gps(local_ref, p->count_us, &pkt_gps_time);
                 ^
src/lora_pkt_fwd.c: In function ‘thread_down’:
src/lora_pkt_fwd.c:2103:62: error: ‘struct tref’ has no member named ‘gps’
                         diff_beacon_time = time_reference_gps.gps.tv_sec % ((time_t)beacon_period);
                                                              ^
src/lora_pkt_fwd.c:2104:73: error: ‘struct tref’ has no member named ‘gps’
                         next_beacon_gps_time.tv_sec = time_reference_gps.gps.tv_sec +
                                                                         ^
src/lora_pkt_fwd.c:2128:21: warning: implicit declaration of function ‘lgw_gps2cnt’ [-Wimplicit-function-declaration]
                     lgw_gps2cnt(time_reference_gps, next_beacon_gps_time, &(beacon_pkt.count_us));
                     ^
src/lora_pkt_fwd.c: In function ‘gps_process_sync’:
src/lora_pkt_fwd.c:2664:5: warning: passing argument 2 of ‘lgw_gps_get’ from incompatible pointer type [enabled by default]
     int i = lgw_gps_get(&utc, &gps_time, NULL, NULL);
     ^
In file included from inc/jitqueue.h:28:0,
                 from src/lora_pkt_fwd.c:51:
../../lora_gateway/libloragw/inc/loragw_gps.h:137:5: note: expected ‘struct coord_s *’ but argument is of type ‘struct timespec *’
 int lgw_gps_get(struct timespec* utc, struct coord_s* loc, struct coord_s* err);
     ^
src/lora_pkt_fwd.c:2664:5: error: too many arguments to function ‘lgw_gps_get’
     int i = lgw_gps_get(&utc, &gps_time, NULL, NULL);
     ^
In file included from inc/jitqueue.h:28:0,
                 from src/lora_pkt_fwd.c:51:
../../lora_gateway/libloragw/inc/loragw_gps.h:137:5: note: declared here
 int lgw_gps_get(struct timespec* utc, struct coord_s* loc, struct coord_s* err);
     ^
src/lora_pkt_fwd.c:2683:5: error: too many arguments to function ‘lgw_gps_sync’
     i = lgw_gps_sync(&time_reference_gps, trig_tstamp, utc, gps_time);
     ^
In file included from inc/jitqueue.h:28:0,
                 from src/lora_pkt_fwd.c:51:
../../lora_gateway/libloragw/inc/loragw_gps.h:149:5: note: declared here
 int lgw_gps_sync(struct tref* ref, uint32_t count_us, struct timespec utc);
     ^
src/lora_pkt_fwd.c: In function ‘gps_process_coords’:
src/lora_pkt_fwd.c:2694:5: error: too many arguments to function ‘lgw_gps_get’
     int    i = lgw_gps_get(NULL, NULL, &coord, &gpserr);
     ^
In file included from inc/jitqueue.h:28:0,
                 from src/lora_pkt_fwd.c:51:
../../lora_gateway/libloragw/inc/loragw_gps.h:137:5: note: declared here
 int lgw_gps_get(struct timespec* utc, struct coord_s* loc, struct coord_s* err);
     ^
src/lora_pkt_fwd.c: In function ‘thread_gps’:
src/lora_pkt_fwd.c:2725:66: error: ‘LGW_GPS_MIN_MSG_SIZE’ undeclared (first use in this function)
         ssize_t nb_char = read(gps_tty_fd, serial_buff + wr_idx, LGW_GPS_MIN_MSG_SIZE);
                                                                  ^
src/lora_pkt_fwd.c:2740:45: error: ‘LGW_GPS_UBX_SYNC_CHAR’ undeclared (first use in this function)
             if(serial_buff[rd_idx] == (char)LGW_GPS_UBX_SYNC_CHAR) {
                                             ^
src/lora_pkt_fwd.c:2745:17: warning: implicit declaration of function ‘lgw_parse_ubx’ [-Wimplicit-function-declaration]
                 latest_msg = lgw_parse_ubx(&serial_buff[rd_idx], (wr_idx - rd_idx), &frame_size);
                 ^
src/lora_pkt_fwd.c:2748:39: error: ‘INCOMPLETE’ undeclared (first use in this function)
                     if (latest_msg == INCOMPLETE) {
                                       ^
src/lora_pkt_fwd.c:2755:46: error: ‘UBX_NAV_TIMEGPS’ undeclared (first use in this function)
                     } else if (latest_msg == UBX_NAV_TIMEGPS) {
                                              ^
src/lora_pkt_fwd.c:2759:46: error: ‘LGW_GPS_NMEA_SYNC_CHAR’ undeclared (first use in this function)
             } else if(serial_buff[rd_idx] == LGW_GPS_NMEA_SYNC_CHAR) {
                                              ^
Makefile:62: recipe for target 'obj/lora_pkt_fwd.o' failed
make[1]: *** [obj/lora_pkt_fwd.o] Error 1
make[1]: Leaving directory '/opt/lora-net/gateway/packet_forwarder-master/lora_pkt_fwd'
Makefile:11: recipe for target 'all' failed
make: *** [all] Error 2
lora@lora-iot-sk /opt/lora-net/gateway/packet_forwarder-master $

I'm a newbie with this, maybe I miss something during the protocol.. If anyone has an idea of ​​my mistake, it will be with pleasure!

Thanks in adavnce, 
Thomas.

**Comment by mcoracin** [comment]
Hello,
There seems to be a mismatch between the packet forwarder and the HAL you are compiling.
You need to get the latest versions of both lora_gateway repository and packet_forwarder repository, and compile both.

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support?__hstc=212684107.579a13689e43099691e328c9248e6ecc.1623103335314.1624470656297.1624635514661.6&__hssc=212684107.6.1624635514661&__hsfp=4176385453] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
