### ISSUE TITLE
How to log info

### ISSUE THREAD

**Issue by richardtomkins** [Lora-net/packet_forwarder#87]
I have looked and looked and am not able to find out how to do the following.

Many people include a log file of dialog that appears to come from the Packet Forwarder. I have seen this here and at TTN and other sites.
The first few characters of the file are INFO:
as seen below.
How are people producing this output and how is it being captured.
I realize this is probably simple, but for the devil, I cannot figure this out.

INFO: Little endian host
INFO: found global configuration file global_conf.json, parsing it
INFO: global_conf.json does contain a JSON object named SX1301_conf, parsing SX1301 parameters
INFO: lorawan_public 1, clksrc 1
INFO: Configuring TX LUT with 16 indexes
...
INFO: Contact email configured to "contact@ch2i.eu"
INFO: Description configured to "ch2i-gw02-ic880a"
INFO: Su

**Comment by mcoracin** [comment]
Those are the logs generated by the packet forwarder on the console.
How to get those, depends on how you run the packet forwarder. If you run it manually, you'll see them immediatly.
Then depending on the gateway you are using and how the packet forwarder is configured to be launched, it may change.
Maybe you can give more detail on what you are using and how...?

**Comment by richardtomkins** [comment]
I will respond in a couple of weeks.
My partner dropped out of the business.
I am in the process of getting set up, again.
As I consider my revised setup, I intend to do a fresh install on the Gateway.
My Gateway is a LoRaGo PORT on a RaspBerry Pi 3 B.
I will set up the Packet Forwarder (Semtech) startup as a service.

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support?__hstc=212684107.579a13689e43099691e328c9248e6ecc.1623103335314.1624470656297.1624635514661.6&__hssc=212684107.6.1624635514661&__hsfp=4176385453] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
