### ISSUE TITLE
I cannot get the beacon successfuly in CLASS B mode

### ISSUE THREAD

**Issue by supercoos** [Lora-net/packet_forwarder#88]
Hi all

I think I have not receive a beacon successfuly,like blew picture shows
![image](https://user-images.githubusercontent.com/33342578/40334606-5059a316-5d91-11e8-88eb-6069f2c4cdf4.png)

![image](https://user-images.githubusercontent.com/33342578/40334728-07752d4a-5d92-11e8-9c7c-9718ff23bbbf.png)

and I use the lora-net:lora_gateway 5.0.1 packet_forwarder4.0.1
anything without change except blew points
1、DEFAULT_BEACON_FREQ_HZ ->471500000 because my board is 470mhz suport
2、I use the lora_pkt_fwd/global_conf.json and add the blew points
“gps_tty_path”: “/dev/ttyAMA0”,
/* GPS reference coordinates /
“ref_latitude”: 0.0,
“ref_longitude”: 0.0,
“ref_altitude”: 0,
/ Beaconing parameters */
“beacon_period”: 128,
3、now it can work well in class A mode，and I can get the right time by the DeviceTimeAns command
4、in 《LoRaMac-node-feature-class_b 》  I only enable the LORAMAC_CLASSB_ENABLED  
5、where is wrong？

other question：
1、the gateway will answer two reply when I send A DeviceTimeReq command？

thank you very much
best regards

**Comment by mcoracin** [comment]
Hello,
- Are the beacon parameters aligned between your end-node and the gateway, according to the LoRaWAN regional specification?
- Is your gateway actually sending the beacons? Do you have a way to monitor that the beacon is being sent?
- Could you attach few minutes of your packet forwarder logs, from the startup to, lets's say, 4 minutes later, the time to sent 2 beacons...?
