### ISSUE TITLE
List of global_conf.json keys

### ISSUE THREAD

**Issue by Mehradzie** [Lora-net/packet_forwarder#9]
Atm, there is no documentation on all the available keys on the **global_conf.json** or the functionality of each  key. 

We have multiple questions in mind that could be answered if we had a very brief documentation, since we are doing lots of guess work. There are tags that we accidentally discovered by looking at multiple different example codes and we would really appreciate it if we could have a list :smile:

Another big question in mind 
We are wondering if we could add a second **mCard** to our **Multitech Conduit** and then expand the packet forwarder to handle it by using another `"SX1301_conf"` key? If so, what is the limit. This would let us to listen to 16 channels simultaneously rather than 8. 

Thanks in advance for your help.

**Comment by dhavalp** [comment]
I am looking for a conf file for RN2483 http://www.microchip.com/DevelopmentTools/ProductDetails.aspx?PartNO=rn-2483-pictail and suggestions for that?

**Comment by melvyn-sopacua** [comment]
@dhavalp The RN2483 isn't a concentrator but end node. Using it as a concentrator/gateway will cause great pain.

**Comment by cirkutninja** [comment]
@Mehradzie  Was curious to know if you had any resolution to your post? I'm also having an issue trying to figure out the functionality of the keys within the global_conf.json files and was wondering if you had an answer?

**Comment by mcoracin** [comment]
There is no documentation available yet.
Until it is the case, I suggest that you ask here for keys which are not clear to you.

Almost all keys end up being a configuration of the lora_gateway HAL, which is somehow documented. You should find the answers for most of the keys.
But we can help for the others.

**Comment by cirkutninja** [comment]
@mcoracin thanks for the info. I'll take a dig around in the HAL and post if I need help, as you suggest.

**Comment by cdliuqiang** [comment]
@mcoracin   there is no global_conf about sx1255,   can you tell me the specific meaning of "tx_lut_x" configuration, and the difference between sx1255 and sx1257 in "tx_lut_x" configuration?

**Comment by mcoracin** [comment]
@cdliuqiang sorry, I don't have those information, you should contact Semtech support on LoRa community.

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support?__hstc=212684107.579a13689e43099691e328c9248e6ecc.1623103335314.1624470656297.1624635514661.6&__hssc=212684107.6.1624635514661&__hsfp=4176385453] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
