### ISSUE TITLE
Time stamps

### ISSUE THREAD

**Issue by gyha** [Lora-net/packet_forwarder#95]
Hello.
I have a question on packet_forwarder time system.
Is it possible to record the tx / rx time in nanoseconds?
Actually, the GW send the ACK to end divice and the end device send the message in the respond with the ACK.
So, i want to know the time (interval) in nanoseconds betwwen ACK(GW) and respond message(End device).

Thank you

**Comment by mcoracin** [comment]
No it's not possible, the maximum precision you can get with sx1301 timestamping is 8µs.
