### ISSUE TITLE
Installing SX1308 on non-standard SPI interface

### ISSUE THREAD

**Issue by hamersin** [Lora-net/packet_forwarder#99]
How can I compile the packet_forwarder to communicate with an SX1308 that is not on SPI interface 0.0.
Is this possible, and what do I have to edit? I am hoping to use SPI 0.1 or SPI 1.0 on the Raspberry PI.

**Comment by mcoracin** [comment]
Update the following line in the HAL, recompile the HAL & packet fowarder:
https://github.com/Lora-net/lora_gateway/blob/a955619271b5d0a46d32e08150acfbc1eed183b7/libloragw/src/loragw_spi.native.c#L57

**Comment by hamersin** [comment]
Thanks! That is what I needed.
